// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZku38E9-tW-VmCBv_mt445jiieumxsDM',
    appId: '1:618635921389:web:b26d4e21e44062fffcc9e4',
    messagingSenderId: '618635921389',
    projectId: 'user-data-cf582',
    authDomain: 'user-data-cf582.firebaseapp.com',
    storageBucket: 'user-data-cf582.appspot.com',
    measurementId: 'G-587T8Z3C59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpWqlbWJ9Ig2yH-AgNKPmJ2qnpfWL08lw',
    appId: '1:618635921389:android:6ff29de2f7eae1fcfcc9e4',
    messagingSenderId: '618635921389',
    projectId: 'user-data-cf582',
    storageBucket: 'user-data-cf582.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUzyigA_V1YiM0GX2w0uGd-wXFfBgnZ2c',
    appId: '1:618635921389:ios:37ac2a699c3de7f3fcc9e4',
    messagingSenderId: '618635921389',
    projectId: 'user-data-cf582',
    storageBucket: 'user-data-cf582.appspot.com',
    iosClientId: '618635921389-7r8agtb1ca9jeqbbeotvbo8l2aoi4um0.apps.googleusercontent.com',
    iosBundleId: 'com.example.userdatastorage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUzyigA_V1YiM0GX2w0uGd-wXFfBgnZ2c',
    appId: '1:618635921389:ios:37ac2a699c3de7f3fcc9e4',
    messagingSenderId: '618635921389',
    projectId: 'user-data-cf582',
    storageBucket: 'user-data-cf582.appspot.com',
    iosClientId: '618635921389-7r8agtb1ca9jeqbbeotvbo8l2aoi4um0.apps.googleusercontent.com',
    iosBundleId: 'com.example.userdatastorage',
  );
}
